appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: hT2hFMTFanjHPYZZ8vhXBH2+eUc01IC0Jeh+g96mWO/Nz7iHFznkMMoP0WD+fhjGo4J1KXrgq5NVptNcLIefnJOnCrT4v+iKurJOL76SveGVuWuLYOFfLSi1Huc3ys06Sz6o/7RhXbjcPRcK653RNQwE6EaiNjUlEZ+3Bv5RAZBcZ3kKLaJ9ngNiNG9gwHb+jBW80uDKrNOqmGj8hyb8jPiir/13Tq5HCOCVkSamPTvVZhH6luXXmBOewP8wOlliJmzRhpsw0TKLiEVuvPe7C4P3bXAGNJ/XEgbvC+a8/6TSlMp7gT+BV4SYWpM+O43Jb5NrXDivGGI2sxO6bIFPqxADhqhKUvfxkFX5Yfmec+wM5UOfBArO9jAOXfmWa3im7jAiu1ngo6MgJH0JiYFSmEzD9lEOIdk3fPXTi9hqzAPQMfRusmaFXspT/nDLJeHlYAbd7wjtiYYrsj6NJlEajakXogviB8U392LaLUlYwKKyWlkTuuWSbAQm5AlIN5vFGBoOvKKw83gCNlnEeFFSmoW8c7bNtFaNNCmxRtCCBP6tG4jnXDZdUmXnIUZbJHM7M4VLx00vk8chsYbRLDAVTLJIcnaLy+7R55x6gT/5cvGp2ICPxkSebqcs+87rcKSgLjLxS7P24dGWrPfffTmlX86WKKOqDS1/c+cFWfSFi64=}
bot:
  automerge: true
